### ISSUE TITLE
Turn Off Github Turn On AWS (production)

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#100]
**Overview**
Finally the time has come.

GHA have served us well but we need to run the code in AWS. Testing should have been done on multiple collections in production. We need to switch of the github actions and switch on Airflow scheduling

**Tech Approach**
A bullet pointed list with details on how this could be technically worked.

- GHA can run a dummy. action instead of the actual one
- Nightly schedule should be. set up in airflow
- once. moved over we should look at removing all of the actions in the current collection repos.
- Relevant accounts need to be set up

**Acceptance Criteria/Tests**

- All collections must be running in production. They should all succeed except title boundaries which is a known issue.
- Github actions should not be running
- Documentation should be created and shared with data management on how to use airflow to trigger collection runs throughout the day
- Documentation for running a collection needs to be updated/created
- Accounts to airflow will need to be set up for all developers in DM and in  infra

**Resourcing & Dependencies**

- This will fundamentally alter how stuff is. running so will impact DM
- We should present this back to stakeholders who use GHAs regularly and show them how it works.
- WE must have a couple devs ready to solve any problems that arise
- **Important: Time estimate assumes no major remedial work required to data collection pipeline containers, Airflow/MWAA provisioning nor ECS cluster**

---

- [x] Schedule daytime run of ONE DAG in production
- [x] Schedule night-time run of ONE DAG in production (turn off GHA)
- [x] Schedule night-time run of FIVE DAGs in production (turn off GHA)
- [x] Schedule night-time run of remaining DAGs in production (turn off GHA)
- [x] Setup accounts to access airflow for all developers in DM and in infra
- [x] Document how to use Airflow to trigger collection runs throughout the day
- [x] Update existing documentation for running a collection
- [x] Update documentation for adding a new collection
- [x] Show & tell on how to run collections

**Comment by Ben-Hodgkiss** [comment]
Merged ticket around updating documentation for adding new collection... Key points from the ticket were:

**Overview**
The current guidance on the wki for creating a collection will need updating to reflect the new process which doesn’t necessitate the creation of a new …-collection repo.

**Approach**

- Update the document to show the new method for creating a collection. This should all be done from (just) the config repo.
- Remove the existing sections on creating collections in centralised and non-centralised collections. The latter is now obsolete, and the former will be when we move to airflow.
- Highlight that this latest update is to allow us to work with Airflow.

**Comment by ernest-tpximpact** [comment]
Ancient woodland scheduled run seems looking fine. [DAG run](https://pipelines.planning.data.gov.uk/dags/ancient-woodland-collection/grid?dag_run_id=manual__2024-10-25T09%3A00%3A06.596483%2B00%3A00&task_id=ancient-woodland-collection&tab=logs)
