### ISSUE TITLE
Connect airflow to slack for notifications

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#101]
**Overview**
Slack is where we push alerts/notifications when pipelines fail. We need to ensure that airflow is capable of alerting us in slack when dags fail. specifically when we run the main scheduler dag can it alert us what failed every day?

**Tech Approach**

- slack can be. called as an on failure call-back for the scheduler DAG
- this will need some configuration in slack which @eveleighoj can help pair on to get it set up correctly
- slack will need configuring in airflow. It could be worth reviewing if terraform can be used to automate this but I don’t think it can
- The message should include links to all failed tasks (if those. tasks are dags then it can link to the tag run)
- Only set this up for prod - not dev or staging

**Acceptance Criteria/Tests**

- if one or more of the dags fail then a message is sent to the slack channel

**Resourcing**
Developer should be able to set up most of this

May need admin access for parts of the task

**Comment by cpcundill** [comment]
Proved notification via Slack yesterday:

https://tpximpact.slack.com/archives/CPTN66SLE/p1733768139696779
