### ISSUE TITLE
Fix datetime for LPA

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#125]
**Overview**

We have seen from an LPA a strange occurrence with datetime. The [endpoint](https://www.stalbans.gov.uk/sites/default/files/documents/publications/planning-building-control/Agile/Tree_Dataset.json) has the dates formatted as YYYY-MM-DDTHH:MM:SS. This is an accepted date that should be converted. However, before it reaches the python code, it is being converted (perhaps by ogr2ogr) into [YYYY/MM/DD HH:MM:SS](https://datasette.planning.data.gov.uk/tree/issue?_sort=resource&field__exact=entry-date). This is currently not accepted.

**Tech Approach**
- Amend digital-land-python and the unit tests to accept this datetime format. @eveleighoj has already created a test in a branch [here](https://github.com/digital-land/digital-land-python/pull/258) when we were investigating this.
- Investigate whether this is happening for ogr2ogr conversion and if we can process the dates as a string prior to this conversion.

**Acceptance Criteria**
- [ ] The St Albans tree dataset processes with no "real date" issues.
- [ ] Test cases are built to ensure that the ogr2ogr date format is accepted by the pipeline.
- [ ] An investigation has been completed into the ogr2ogr conversion to try and have the pipeline process the raw date from the endpoint and not the converted one. This may require new tickets in the backlog.
- [ ] @Ben-Hodgkiss is informed once St Albans is working correctly - he can then inform the Providers team that this is fixed.

**Comment by ssadhu-sl** [comment]
The time formats accepted in the date.py has "%Y/%m/%d %H:%M:%S%z" which expects a timezone offset at the end. But the endpoint provided by LPA has no timezone so the format fit for it would be "%Y/%m/%d %H:%M:%S".

**Comment by ssadhu-sl** [comment]
very similar issue: https://github.com/OSGeo/gdal/issues/2403
