### ISSUE TITLE
New expectation: conservation-area count comparison

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#130]
**Overview**

Data management need a new data quality assessment in the pipeline to compare the number of entities within the boundary of each LPA with the expected number. 

The manual reference counts which should be used as the expected number for each LPA are [here](https://docs.google.com/spreadsheets/d/e/2PACX-1vSGZIudsGx0ez4cU-4wSvymvXIFfpDb_qfbS3uW5RiuBkJrJQ9D8k0HBUPtgncRXA/pub?gid=485605871).

And a jupyter-notebook doing this calculation is [here](https://github.com/digital-land/jupyter-analysis/blob/main/analysis/2024-07_conservation_area_count_comparison/conservation_area_count_comparison%20-%20analysis.ipynb). 

Some anticipated challenges to resolve:
- which LPA boundaries to use as the starting point for the check
- how to represent the results in the current issues/expectations tables.

**Tech Approach**
To be completed by dev.

**Acceptance Criteria/Tests**
- We should be able to see any organisation where the actual vs. expected numbers don’t match, and what the difference is.
- Handover occurs between Infrastructure and Data Management.

**Comment by Ben-Hodgkiss** [comment]
Linked Jira ticket: https://mhclgdigital.atlassian.net/browse/DATA-900

**Comment by alexglasertpx** [comment]
New expect.csv file has been built using data from the google doc. Attached python script was used to create it.[expect_script.txt](https://github.com/user-attachments/files/18082664/expect_script.txt) Note that this is saved as a text file as cannot save Python scripts here.

After speaking with data management, there is a debate to be had whether we want to check if the geometric relationship should be 'within' or 'intersects'. Either way that is used only produces a few dozen answers where the expected value and the actual value actually match, though this is understood (for example, some data is out of date, for some councils we don't have any data).

**Comment by alexglasertpx** [comment]
Waiting for confirmation from data management whether to use `intersects` or `within`

**Comment by alexglasertpx** [comment]
Have merged onto the config repo.
