### ISSUE TITLE
Bug: OS Base Layer not showing when zoomed out

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#137]
**Overview**

On 28/10/2024, it was noticed that the base layer of the Planning Data Map did not display if the zoom level was beyond 6. If zoomed in, the OS map did show but then disappeared after zooming out again. @GeorgeGoodall-GovUk fixed some opacity values that were causing map errors in the console, however the issue has persisted, prompting a more detailed investigation to begin.

**Tech Approach**
- ‌

**Acceptance Criteria/Tests**
- Upon being fixed, the map of England should show at all acceptable zoom levels.

**Resourcing**
Requires potential front and back-end resource.

**Comment by ssadhu-sl** [comment]
@GeorgeGoodall-GovUk is adding a fix where by default the map will be loaded at the working zoom level. This is a temporary fix and this might need to be investigated further on what is causing the issue.

**Comment by GeorgeGoodall-GovUk** [comment]
https://github.com/digital-land/digital-land.info/pull/314
PR created to change the min zoom level. all works fine now. slightly more zoomed in by default but not by much
happy to investigate the reasons behind this further but a request for that work will need to go through @CharliePatterson
