### ISSUE TITLE
Entity Number Relation

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#142]
**Overview**
The Providers team would like to be able to use entity numbers when creating issues. This will mean that the entity assignment needs to be moved in the pipeline to an earlier stage. @eveleighoj has begun some research on this and believes it is possible!

Pull Request(PR): <insert link to pull request when opened>

**Tech Approach**

* Issues are written at an entry level (technically an entry-field level) and given that each entry has to be provided an entity in order to turn it into a set of facts we should also be able to provide the entity in the issues table. 
* when an entity is not assigned an issue cannot be given an entity therefore it will be blank and should be able to be blank.

There are two main approaches to do this:

* at the entity assignment stage retrospectively apply entity numbers to all issues from that entry. This could be difficult but would be the least impactful way. of doing it.
* The log is stored in memory until the end of the process so can be retrospectively updated until that point.
* move the entity assignment phase earlier in the process to attempt to assign an entity number before other issues are raised. You need to be careful on the order of the phases with this approach. E.g. The organisation phase has to happen before entity. assignment. 

There are issues being assigned outside of the main pipeline that it's worth looking out for.

**Acceptance Criteria/Tests**
- Each issue has a corresponding entity number
- issues where the entry's entity is unknown don't have an entity number
- minimal changes to which issues are raised.

**Resourcing & Dependencies**
- Providers must be informed to test prior to implementation
- DM should take a look too

**Comment by gmatchett** [comment]
files have been shared with @GeorgeGoodall-GovUk and he was happy
