### ISSUE TITLE
Ensure values with invalid coordinate errors are not used in facts

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#150]
**Description:** Service users have warned that brownfield land data has lots of entities with points well outside of England. It appears that these are correctly being identified by the pipeline as data quality issues with the “invalid coordinate”, or “..out of bounds of England” issue types, but even though these issues type have an “error” severity the values are still ending up as facts on live entities. 

**For example:**

entity [1700497](https://www.planning.data.gov.uk/entity/1700497) has a point value of POINT (3974021.813 -8522.251), which comes from fact [f36bcd38ba79bd0c9af917706b26810be1d3404e4f7a1937c7ac49282076f2cd](https://www.planning.data.gov.uk/fact/f36bcd38ba79bd0c9af917706b26810be1d3404e4f7a1937c7ac49282076f2cd?dataset=brownfield-land). The resource that generated this fact [has invalid coordinate issues raised](https://datasette.planning.data.gov.uk/brownfield-land/issue?_sort=rowid&resource__exact=06323d848513172ef08e6362d29f0476a2b53d57e2a432e2c7e1f6533f81d5b5) for entry 10.

entity [1701854](https://www.planning.data.gov.uk/entity/1701854) has a point value of POINT (54.396 -5.681), which comes from fact [6caea4152b2e1f1d8c800eecefc4d6a72f195abb61eb1aac7b8561bec4654256](https://www.planning.data.gov.uk/fact/6caea4152b2e1f1d8c800eecefc4d6a72f195abb61eb1aac7b8561bec4654256?dataset=brownfield-land). The resource that generated this fact [has “WGS84 out of bounds of England” issues](https://datasette.planning.data.gov.uk/brownfield-land/issue?_sort=rowid&resource__exact=d86d8d0dfc5ae7426838a785d05257aff9f72d0d1c02823d517a99908e9178e3) for entry 6.

**Priority:** high

**Recommended Resolution:** Make sure that when a value has an “invalid coordinate” issue type it is not used to create a fact.

**Tech Approach**

In PivotPhase, check the line-number and entry-number to see if they are in the issue log. The issue log will need to be passed in, and a way added to get the issue for a given line/entry (if present). The issue log is stored in-memory at this point. Facts that have issues will not be emitted.

**Success Criteria:**
- Fix made to the pipeline so that invalid points don’t appear with entities on the platform
- Move ticket to weekly review column, and tag Swati.
- Add any new processes which need to be repeated into the operations manual.

**Comment by cjohns-scottlogic** [comment]
Do we also want to not use values with other issues, such as OSGB out of bounds?

**Comment by Ben-Hodgkiss** [comment]
PR is: https://github.com/digital-land/digital-land-python/pull/306
