### ISSUE TITLE
Local Plans Platform Update: Change to Local Plan Boundary entity template

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#153]
**Overview**
From the updates required to the platform to allow for better usage for Local Plans. We need to amend the `local-plan-boundary` entity template to include a table of any `local-plan` entities that are related to that boundary.
For example:
- South Cambridgeshire have a local plan on the platform [here](https://www.planning.data.gov.uk/entity/4220006). This entity lists the Local Plan Boundary as E07000012.
- The South Cambridgeshire District Council Local Plan Boundary entity can be found [here](https://www.planning.data.gov.uk/entity/4211006). This has the reference E07000012. 
- From the Local Plan Boundary page for E07000012, we should be able to see a table with links to any and all Local Plans that list the boundary as E07000012.

Further details on this can be found [here](https://github.com/digital-land/digital-land/discussions/349#discussioncomment-11291005).

**Tech Approach**

**Frontend:**
- Create a table 'local-plan' on the local-plan-boundry page. https://www.planning.data.gov.uk/dataset/ancient-woodland-status
- Columns: local-plan name, documentation-url

**Backend:**
- Fetch all the local plans for local-plan-boundry. Local plan contains a field called local-plan-boundry (check search_entities API if you can modify it, use the ORM) <Do not add a new API>
- Add test cases

**Acceptance Criteria**

- From the local plan boundary entity page, you can see a table with links to any local plans with the same boundary.
- The page template is updated on a branch alongside the other Local Plans Platform Update. This branch should then be deployed to development for user feedback. This ticket can be closed when the branch is in development. A further ticket will be created to handle the feedback and eventual deployment into production.

**Frontend**
- [x] Add a new table 'local-plan' on 'local-plan-boundary' page
- [x] Add Columns: reference, local-plan name, documentation-url
- [x] Link reference to local-plan page

**Backend**
- [x] Fetch all related local-plans for a local-boundary in entity page
- [x] add the list as a response to entity.html page
- [x] Link the local plan boundary field on local plan entity page to its associated local plan boundary entity page 
- [x] Add test cases

**Comment by ssadhu-sl** [comment]
Mural board created: https://app.mural.co/t/mhclg2837/m/mhclg2837/1732097528707/38ae72c452aeb7209b5ee32ce90d88fa78b58cab
