### ISSUE TITLE
Local Plans Platform Update: Change to Local Plan entity template

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#154]
**Overview**
From the updates required to the platform to allow for better usage for Local Plans. We need to amend the `local-plan` entity template to include the following:

- Where the local plan lists a local plan boundary, the `local-plan` entity page should show the map view of that boundary. I.e. for South Cambridgeshire local plan [entity](https://www.planning.data.gov.uk/entity/4220006), we should show the boundary displayed on the `local-plan-boundary` [entity page](https://www.planning.data.gov.uk/entity/4211006).
- We should add a table showing links to any `local_plan_document` entities which link to the local plan. I.e. for South Cambridgeshire local plan [entity](https://www.planning.data.gov.uk/entity/4220006), we should show a table that contains any Local plan documents that have Local plan = `south-cambridgeshire-district-council-local-plan`, for example, this [document entity](https://www.planning.data.gov.uk/entity/3800109) (amongst others).
- We should add a table showing links to any `local-plan-timetable` entities that link to the plan. For example, for the [Islington Local Plan entity](https://www.planning.data.gov.uk/entity/4220001), it should include (amongst others) this [start of public consultation timetable entity](https://www.planning.data.gov.uk/entity/4230012). This table should be contain the `event-date` field and be ordered by the `event-date`.

Further details on this can be found [here](https://github.com/digital-land/digital-land/discussions/349#discussioncomment-11291280).

**Tech Approach**

**Frontend:**
- Create a table 'local-plan-document' on the local-plan page.
- Create a table 'local-plan-timetable' on the local-plan page.
- Columns: name, category, and document-url
- Add Map view on local plan same as local-plan-boundry (confirm?)

**Backend:**
- Fetch all the local plan-documents for a local-plan. Local plan document contains a field called local-plan (check search_entities API if you can modify it, use the ORM) <Do not add a new API>
- Fetch all the local plan-timetables for a local-plan. Local plan timetable contains a field called local-plan. (check search_entities API if you can modify it, use the ORM) <Do not add a new API>
- For local-plan-timetable, make sure to return event-date and result is ordered by event-date.
- Create a link to local-plan-boundry on the local-plan entity page
- Add test cases

**Acceptance Criteria**

- From the local plan entity page, you can see a map that displays the boundary found on the linked local plan boundary entity.
- From the local plan entity page, you can see a table showing any and all local plan documents that are linked to the local plan.
- From the local plan entity page, you can see a table showing any and all local plan timetable entities, displayed in event-date order.
- The page template is updated on a branch alongside the other Local Plans Platform Update. This branch should then be deployed to development for user feedback. This ticket can be closed when the branch is in development. A further ticket will be created to handle the feedback and eventual deployment into production.

**Frontend**
- [x] Add a new table 'local-plan-document' on 'local-plan' page
- [x] Add a new table 'local-plan-timetable' on 'local-plan' page
- [x] Add Columns on both tables: reference, name, category, document-url
- [x] Add Map view on local-plan page showing same as local-plan-boundary map

**Backend**
- [x] Fetch all related local-plan-documents for a local-plan in entity page
- [x] Fetch all related local-plan-timetables for a local-plan in entity page
- [x] Order by event-date in local-plan-timetable
- [x] add the lists as a response to entity.html page
- [x] Create a link on local-plan-boundary field on the local-plan entity page
- [x] Add test cases

**Comment by ssadhu-sl** [comment]
Mural board created: https://app.mural.co/t/mhclg2837/m/mhclg2837/1732097528707/38ae72c452aeb7209b5ee32ce90d88fa78b58cab
