### ISSUE TITLE
Spike: Fix insufficient data problem with response time alarm

### ISSUE THREAD

**Issue by cpcundill** [digital-land/technical-documentation#157]
**Overview**

Attempt to fix insufficient data problem with response time alarm.

**Background**

Currently when there is insufficient data for the response-time alarm, a register notification is triggered to Slack.  Ideally we wouldn't have the scenario of insufficient data - no log records to derive response time should be interpreted as a zero response time.

**Tech Approach**

- [x] Confirm register notification is caused by insufficient data
- [x] Investigate possibility of interpreting insufficient data as a zero response time.
- [x] Make necessary Terraform changes to relevant CloudWatch Log Filter and rollout to production (if fix is straightforward)

**Acceptance Criteria/Tests**

- Agreed next steps to implement a fix are added a comment on this issue

**Resourcing**

-  this will primarily be a devops ticket due to the terraforming required
- Application development assistant should be available for checking the application code.

---

**Ticket Management - DELETE** this section once completed

- Complete all relevant tags - make sure Infrastructure is tagged so it is picked up by our filters!
- Complete the time estimate field
- Make sure you have a PR link in the Overviewabove.
- If relevant, link to the relevant OKR as an attachment.
- Link to any tickets in other boards that are dependent on it.

**Comment by ernest-tpximpact** [comment]
Missing data in the cloudwatch alarm seems to cause the alarm to go into an **Insufficient Data** state becuase there isn't enough data to determine whether the alarm is in the OK or ALARM state. WIll set **TreatMissingData** parameter as "ignore", this should ignore missing data and maintain the current state of the alarm.
