### ISSUE TITLE
Increase CPU capacity

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#169]
**Overview**
We have observed sporadic spikes in CPU utilisation of the async request processor during the Infrastructure Review calls, We need to determine whether these are driven by the queries and resources being used or if there is an underlying issue causing the spikes in CPU utilisation. We propose temporarily increasing CPU allocation for two weeks.

Following the two weeks, we will review CPU utilisation at the Infrastructure Review. We expect there will be two possibilities:

1. **If spikes are reduced in percentage terms:** We may need to implement a permanent CPU increase - % to be determined when looking at the data.
2. **If spikes persist at close to 100% utilisation:** This could suggest an underlying issue requiring further investigation into root causes.

**Tech Approach**
- To be completed during refinement

**Acceptance Criteria**
- CPU increased (2vcpu) for async request processor for a two week period.
- A follow-up ticket is created to analyse post-change CPU utilisation in a future sprint, with baseline metrics included for comparison.

**Comment by ernest-tpximpact** [comment]
Production now upgraded to 2cCPU on 6th Dec 11am
