### ISSUE TITLE
Local Plans - Make amends and publish

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#170]
**Overview**
Following the first design of the Local Plans changes, we have received feedback from Data Design. We should implement this, push it back onto the dev branch for final approval and then deploy to all environments.

1. We need to link the local-plan-timetable to local-plan-event. This means that on the timeline on the local-plan page, we can pull through the "nice" name of the local-plan-timetable into the "Name" column. For example, this [entity](https://www.planning.data.gov.uk/entity/4230000) has a local-plan-event field which contains `timetable-published`. This should link to the reference field on this local-plan-event [entity](https://www.planning.data.gov.uk/entity/2950006), and then return the "Name" field (i.e. Local development scheme published).
2. For the table showing the local-plan-timetable on the local-plan page, we need to explore two options:
    2.1. The best option is for us to implement the Timeline component (seen [here](https://digital-land.github.io/design-system/components/timeline/)). This should only return the timetable entries that exist, and return the Name (from the local-plan-event, see edit 1 above), the date (in DD Month YYYY format) and a link to the timetable entity reference. This should be sorted to have the latest date at the top.
    2.2. If this is not possible, we should amend the existing table to the following order: Entity, Name, Event date, Reference (sorted by most recent at the top). 

Full feedback from the Data Design team can be found on this Mural: https://app.mural.co/t/mhclg2837/m/mhclg2837/1732876930545/82cb2ebb43f656165a458eeffda4c5357b340330?sender=ube3e0e01af4ee57c98d22081

**Tech Approach**
- Fetch the local-plan-event table for 'local-plan-event' field in local-plan-timetable
- Display the name from local-plan-event table
- Change the display of local-plan-timetable table in local-plan entity page according to [here](https://digital-land.github.io/design-system/components/timeline/)

**Acceptance Criteria**

- [x] Local-plan-event is linked to the local-plan-timetable (and therefore to local-plan)
- [x] We have reconfigured the timetable following one of the standards above (ideally the timetable component, otherwise the edits to the table)
- [x] Final version deployed to dev and sent to Data Design for review
- [ ] Deployment to all environments

**Comment by gmatchett** [comment]
Fabia and Colm are reviewing
