### ISSUE TITLE
Download of Providers data

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#176]
**Overview**
We've had a request from the Providers team for a download of some data on the Check service. This was requested over the summer and now has Google Analytics, however they need to plug the gap between the past data-drop and Google Analytics being turned on.

**What:** Extract list of file names and URLs that have been run through the check tool, along with the date/time stamp. Period covering: 08/08/24 to present day. (Additional question: is there any other metadata attached to this? e.g. page referrer)
**Why:** To enable us to perform some rudimentary analysis on who has used the check tool, for which datasets, and when. This is a one-off request, to cover the period where we didn't have GA set up.

The previous data that was provided can be found here: https://docs.google.com/spreadsheets/d/1oI4ogzZck5EJG0ufQlLFokmDABT__Co5YkvXX_cgpNQ/edit?gid=1201690491#gid=1201690491

**Comment by ernest-tpximpact** [comment]
having connectivity issues in production either database clone and create from snapshot doesnt work even in our public network.

**Comment by ernest-tpximpact** [comment]
extract - https://mhclg-my.sharepoint.com/:x:/g/personal/ernest_man_communities_gov_uk/EUhiOMl7kF1HryLr7_qurK4B292rztTSSajoj2DJP6ICRw?e=eV3WnE
