### ISSUE TITLE
Jira Ticket - Help with API

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#178]
**Overview**
A PropTech company has got in touch via Jira Service Desk (ticket [DLSD-1161](https://mhclgdigital.atlassian.net/browse/DLSD-1161)) with a question about the API.

<details><summary>JIRA TIcket Details</summary>
<p>

We were advised to use latitude and longitude data to return data but we’ve tried various locations and it’s returning the same empty response.  

Test data - 34 Endcliffe Grove Avenue S10 3EJ. Coordinates (latitude, longitude) - 53.370339682374095, -1.5140470438586133 

Response;  

{
"entities": [],
"links": {},
"count": 0
}

However when I search api with entity number it retuning response like this:

{
"entities": [
{
"entry-date": "2024-06-26",
"start-date": "2015-04-01",
"end-date": "",
"entity": 1,
"name": "Old Oak and Park Royal Development Corporation",
"dataset": "development-corporation",
"typology": "organisation",
"reference": "Q20648596",
"prefix": "wikidata",
"organisation-entity": "1",
"geometry": "",
"point": "",
"twitter": "oldoakparkroyal",
"website": "[https://www.london.gov.uk/about-us/organisations-we-work/old-oak-and-park-royal-development-corporation-opdc](https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.london.gov.uk%2Fabout-us%2Forganisations-we-work%2Fold-oak-and-park-royal-development-corporation-opdc&data=05%7C02%7Cdigitalland%40communities.gov.uk%7C9c3b7a8610fe4b4f3fc508dd194a9c46%7Cbf3468109c7d43dea87224a2ef3995a8%7C0%7C0%7C638694530425381591%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=4GZqCyCgIWJsGMRlfx2FGbJncJeXa5DLhKN3uGUgYQY%3D&reserved=0)",
"wikidata": "Q20648596",
"wikipedia": "Old_Oak_and_Park_Royal_Development_Corporation",
"parliament-thesaurus": "424485",
"statistical-geography": "E51000002",
"opendatacommunities-uri": "[http://opendatacommunities.org/id/dev-corp/old-oak-and-park-royal](https://gbr01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fopendatacommunities.org%2Fid%2Fdev-corp%2Fold-oak-and-park-royal&data=05%7C02%7Cdigitalland%40communities.gov.uk%7C9c3b7a8610fe4b4f3fc508dd194a9c46%7Cbf3468109c7d43dea87224a2ef3995a8%7C0%7C0%7C638694530425410815%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=JiRK30tLQjOtzqq19C5%2BllzTwTIH7chmht%2Bl8TtXRRM%3D&reserved=0)",
"local-planning-authority": "E60000330"
}
],
"links": {},
"count": 1
}

</p>
</details> 

**Tech Approach**

**Acceptance Criteria**

- [x] Investigate API query and confirm results
- [ ] Draft response to be sent via JIRA back to the PropTech Company
- [ ] Inform @Ben-Hodgkiss or @gmatchett to send via Jira
- [ ] Inform @kieranwint once complete as they are liaising with the company

**Comment by ssadhu-sl** [comment]
@Ben-Hodgkiss @gmatchett 

I’m not sure what parameters they are providing, but it seems they’re only passing the latitude and longitude, which ends up querying the entire table:
https://www.planning.data.gov.uk/entity.json?longitude=-1.5140470438586133&latitude=53.370339682374095
This takes a long time to load and often results in a timeout.

For a quicker resolution, they could include the dataset parameter if possible, as this works fine:
https://www.planning.data.gov.uk/entity.json?longitude=-1.5140470438586133&latitude=53.370339682374095&dataset=conservation-area

In the meantime, I’ll look into optimizing this. But this is again due to querying the entire dataset which means querying on heavy datasets like flood-risk-zone

**Comment by Ben-Hodgkiss** [comment]
Initial response sent. Will update ticket in backlog with details for further investigation.
