### ISSUE TITLE
Design Terraform code & state refactor

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#74]
**Overview**

Our infrastructure codebase - digital-land-infrastructure - which is implemented with Terraform has grown organically over the past few years.  Having a single large codebase and Terraform state file makes team working difficult and changes longer to implement.

In order to improve both efficiency and collaborative working, a new design for structuring the Terraform code and state is required along with a refactoring plan.

**Tech Approach**

- Analyse different methods for splitting a large Terraform codebase including handling state migration
- Diagrams for current state (as-is) and proposed (to-be)
- Create design proposal 
- Draft GitHub tickets for refactoring work

**Acceptance Criteria/Tests**

- A new Terraform code architecture design published to the Digital Land Tech Docs site via a design proposal
- A sequential plan with key stages/milestones for refactoring from the current to desired state attached to this card
- GitHub tickets added for each refactoring stage

**Resourcing**
Are there any tickets that need to be completed before this one can be? Are there any limitations as to who in the team can complete this ticket?

AWS / DevOps engineers

**Ticket Management**
DELETE this section once completed

- Complete all relevant tags - make sure Infrastructure is tagged so it is picked up by our filters!
- Complete the time estimate field
- Make sure you have a PR link in the comments.
- If relevant, link to the relevant OKR as an attachment.
- Link to any tickets in other boards that are dependent on it - i.e. Data Management or Providers tickets

**Comment by cpcundill** [comment]
Drafting discussion with design proposal here:

https://github.com/digital-land/technical-documentation/discussions/181
