### ISSUE TITLE
Investigate AWS tagging for billing

### ISSUE THREAD

**Issue by Ben-Hodgkiss** [digital-land/technical-documentation#76]
**Overview**
Although we have implemented tagging on AWS for billing, the vast majority of the costs are still untagged and so we cannot properly track where costs are coming from.

We need to investigate further as to why the tagging set-up is missing most of the costs, providing us with limited data to make decisions on.

**Tech Approach**
A bullet pointed list with details on how this could be technically worked.

- Include links to relevant webpages, github files, user guides etc...
- Person raising the ticket to have a first pass at this (if they know the approach) - Tech Lead will then review and bring to refinement session.

**Acceptance Criteria/Tests**
A bullet pointed list of either acceptance criteria or tests (or both) that will demonstrate that the ticket is resolved.

**Resourcing & Dependencies**

- Are there any tickets that need to be completed before this one can be?
- Are there any limitations as to who in the team can complete this ticket?
- Are there any dependencies on other teams to assist, approve or be handed over to once deployed?

---

**Ticket Management - DELETE** this section once completed

- Complete all relevant tags - make sure Infrastructure is tagged so it is picked up by our filters!
- Complete the time estimate field
- Make sure you have a PR link in the Overviewabove.
- If relevant, link to the relevant OKR as an attachment.
- Link to any tickets in other boards that are dependent on it.

**Comment by ernest-tpximpact** [comment]
Some aws tags were missing from the application task definition while enable the tags but the deployment doesnt seems to trigger. Currently investigate the issue in dev

**Comment by ernest-tpximpact** [comment]
The application task def is now tagged with the relevant tags

**Comment by ernest-tpximpact** [comment]
![Image](https://github.com/user-attachments/assets/40e707a3-afb4-4723-b9c8-d2a4f06f807e)

- ECS cluster nodes tagged
- launch template tagged
- Elastic Block Store volumes for EC2 tagged

as see from the above, we have now tagged most aws resources

**Comment by ernest-tpximpact** [comment]
All terraform changes now apply to dev, will raise PR for staging and production

**Comment by ernest-tpximpact** [comment]
Terraform changes now applied to production. All ECS nodes/resources updated with the latest changes. However, the tasks/servcies will not pick up the new tags until new deployment is being made.
